/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author windows
 */
public class add_techno extends javax.swing.JFrame {
koneksi kon;
    /**
     * Creates new form register
     */
    public add_techno() {
        kon = new koneksi();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        konf_pw = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        link = new javax.swing.JLabel();
        TF_title = new javax.swing.JTextField();
        pw_konf = new javax.swing.JPasswordField();
        BT_cancel = new javax.swing.JButton();
        BT_add = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA_isi = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(775, 512));
        setPreferredSize(new java.awt.Dimension(775, 512));
        setResizable(false);
        setSize(new java.awt.Dimension(775, 512));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        konf_pw.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        konf_pw.setText("Konfirmasi Password Admin");
        getContentPane().add(konf_pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 210, 40));

        title.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        title.setText("Judul Artikel");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 38));

        link.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        link.setText("Isi Artikel");
        getContentPane().add(link, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, 38));
        getContentPane().add(TF_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 480, 40));
        getContentPane().add(pw_konf, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 260, 29));

        BT_cancel.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        BT_cancel.setText("Cancel");
        BT_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BT_cancelMouseClicked(evt);
            }
        });
        getContentPane().add(BT_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 113, 38));

        BT_add.setBackground(new java.awt.Color(255, 255, 255));
        BT_add.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        BT_add.setText("Add");
        BT_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BT_addMouseClicked(evt);
            }
        });
        getContentPane().add(BT_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 113, 38));

        TA_isi.setColumns(20);
        TA_isi.setRows(5);
        jScrollPane1.setViewportView(TA_isi);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 480, 130));

        jLabel1.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        jLabel1.setText("Kategori: Techno");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ttt.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 95, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 36, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_cancelMouseClicked
           this.setVisible(false);
           new home_admin().setVisible(true);
       
    }//GEN-LAST:event_BT_cancelMouseClicked

    private void BT_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_addMouseClicked
        String pw = pw_konf.getText();
        String title = TF_title.getText();
        String link = TA_isi.getText();
        try{
            Statement st = kon.con.createStatement();
            ResultSet result = st.executeQuery("select * from admin_id where password= '"+pw+"'");
            if(result.next()){
            if(pw_konf.getText().equals(result.getString("password"))){
                
            String regist = "insert into content_id (id_konten, title_id, kategori, isi, likes, views) values (id_konten, '"+title+"', 'techno', '"+link+"', likes, views)";
            st.executeUpdate(regist);
            JOptionPane.showMessageDialog(rootPane, "Data Berhasil ditambahkan! ");
            
            this.setVisible(false);
            new home_admin().setVisible(true);
            }}
            else{JOptionPane.showMessageDialog(this,"Password Admin salah!");}
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error: "+e.getMessage());
        }
    }//GEN-LAST:event_BT_addMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_techno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_techno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_techno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_techno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add_techno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_add;
    private javax.swing.JButton BT_cancel;
    private javax.swing.JTextArea TA_isi;
    private javax.swing.JTextField TF_title;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel konf_pw;
    private javax.swing.JLabel link;
    private javax.swing.JPasswordField pw_konf;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
