/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author windows
 */
public class edit_profil extends javax.swing.JFrame {
koneksi kon;
    /**
     * Creates new form register
     */
    public edit_profil() {
        kon = new koneksi();
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        nama_user = new javax.swing.JLabel();
        email_user = new javax.swing.JLabel();
        BT_save = new javax.swing.JButton();
        BT_cancel = new javax.swing.JButton();
        email_user1 = new javax.swing.JLabel();
        TF_namauser = new javax.swing.JTextField();
        TF_emailuser = new javax.swing.JTextField();
        TF_username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        title.setText("EDIT PROFIL");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, 38));

        nama_user.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        nama_user.setText("Nama");
        getContentPane().add(nama_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, 38));

        email_user.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        email_user.setText("E-mail");
        getContentPane().add(email_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, 38));

        BT_save.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        BT_save.setText("Save");
        BT_save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BT_saveMouseClicked(evt);
            }
        });
        getContentPane().add(BT_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 113, 38));

        BT_cancel.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        BT_cancel.setText("Cancel");
        BT_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BT_cancelMouseClicked(evt);
            }
        });
        getContentPane().add(BT_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 113, 38));

        email_user1.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        email_user1.setText("Konfirmasi Username");
        getContentPane().add(email_user1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, 38));
        getContentPane().add(TF_namauser, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 180, 26));
        getContentPane().add(TF_emailuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 180, 26));
        getContentPane().add(TF_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 180, 26));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pf.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 120, 110));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 480));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_saveMouseClicked
        String us_name = TF_namauser.getText();
        String us_email = TF_emailuser.getText();
        String username = TF_username.getText();
        try{
            Statement st = kon.con.createStatement();
            ResultSet result = st.executeQuery("select * from user_id where username= '"+username+"'");
            if(result.next()){
            if(TF_username.getText().equals(result.getString("username"))){
            String ubah = "update user_id set nama = '"+us_name+"', email = '"+us_email+"' where username = '"+username+"'";
            st.executeUpdate(ubah);
            JOptionPane.showMessageDialog(this,"Data Berhasil di Update!");
            this.setVisible(false);
            new navbar().setVisible(true);
            }
            else{JOptionPane.showMessageDialog(this,"Username tidak sama!");}
            }
            else{JOptionPane.showMessageDialog(this,"Username tidak sama!");}
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error: "+e.getMessage());
        }
    }//GEN-LAST:event_BT_saveMouseClicked

    private void BT_cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_cancelMouseClicked
        this.setVisible(false);
        new navbar().setVisible(true);
    }//GEN-LAST:event_BT_cancelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(edit_profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(edit_profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(edit_profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(edit_profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new edit_profil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_cancel;
    private javax.swing.JButton BT_save;
    private javax.swing.JTextField TF_emailuser;
    private javax.swing.JTextField TF_namauser;
    private javax.swing.JTextField TF_username;
    private javax.swing.JLabel email_user;
    private javax.swing.JLabel email_user1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nama_user;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
