/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author windows
 */
public class home_user extends javax.swing.JFrame {
koneksi kon;
    /**
     * Creates new form login
     */
    public home_user() {
        kon = new koneksi();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ST_Job = new javax.swing.JButton();
        ST_Campus = new javax.swing.JButton();
        ST_Ormawa = new javax.swing.JButton();
        ST_Event = new javax.swing.JButton();
        ST_Techno = new javax.swing.JButton();
        ST_Journal = new javax.swing.JButton();
        StudentCampus = new javax.swing.JLabel();
        StudentOrmawa = new javax.swing.JLabel();
        StudentEvent = new javax.swing.JLabel();
        StudentTechno = new javax.swing.JLabel();
        StudentJournal = new javax.swing.JLabel();
        StudentJob = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(775, 512));
        setPreferredSize(new java.awt.Dimension(775, 512));
        setResizable(false);
        setSize(new java.awt.Dimension(775, 512));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ST_Job.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job.png"))); // NOI18N
        ST_Job.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ST_JobMouseClicked(evt);
            }
        });
        getContentPane().add(ST_Job, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, 190, 90));

        ST_Campus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/campus.png"))); // NOI18N
        ST_Campus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ST_CampusMouseClicked(evt);
            }
        });
        getContentPane().add(ST_Campus, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 190, 90));

        ST_Ormawa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ormawa.jpg"))); // NOI18N
        ST_Ormawa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ST_OrmawaMouseClicked(evt);
            }
        });
        getContentPane().add(ST_Ormawa, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 190, 90));

        ST_Event.setIcon(new javax.swing.ImageIcon(getClass().getResource("/event.png"))); // NOI18N
        ST_Event.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ST_EventMouseClicked(evt);
            }
        });
        getContentPane().add(ST_Event, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 190, 90));

        ST_Techno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techno.png"))); // NOI18N
        ST_Techno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ST_TechnoMouseClicked(evt);
            }
        });
        getContentPane().add(ST_Techno, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 190, 90));

        ST_Journal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/journal.jpg"))); // NOI18N
        ST_Journal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ST_JournalMouseClicked(evt);
            }
        });
        getContentPane().add(ST_Journal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 190, 90));

        StudentCampus.setFont(new java.awt.Font("Tekton Pro", 0, 12)); // NOI18N
        StudentCampus.setForeground(new java.awt.Color(255, 255, 255));
        StudentCampus.setText("Student Campus");
        getContentPane().add(StudentCampus, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        StudentOrmawa.setFont(new java.awt.Font("Tekton Pro", 0, 12)); // NOI18N
        StudentOrmawa.setForeground(new java.awt.Color(255, 255, 255));
        StudentOrmawa.setText("Student Ormawa");
        getContentPane().add(StudentOrmawa, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, -1, -1));

        StudentEvent.setFont(new java.awt.Font("Tekton Pro", 0, 12)); // NOI18N
        StudentEvent.setForeground(new java.awt.Color(255, 255, 255));
        StudentEvent.setText("Student Event");
        getContentPane().add(StudentEvent, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        StudentTechno.setFont(new java.awt.Font("Tekton Pro", 0, 12)); // NOI18N
        StudentTechno.setForeground(new java.awt.Color(255, 255, 255));
        StudentTechno.setText("Student Techno");
        getContentPane().add(StudentTechno, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, -1, -1));

        StudentJournal.setFont(new java.awt.Font("Tekton Pro", 0, 12)); // NOI18N
        StudentJournal.setForeground(new java.awt.Color(255, 255, 255));
        StudentJournal.setText("Student Journalism");
        getContentPane().add(StudentJournal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        StudentJob.setFont(new java.awt.Font("Tekton Pro", 0, 12)); // NOI18N
        StudentJob.setForeground(new java.awt.Color(255, 255, 255));
        StudentJob.setText("Student Job");
        getContentPane().add(StudentJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/navbar.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 30, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tt.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        this.setVisible(false);
        new navbar().setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void ST_CampusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ST_CampusMouseClicked
        this.setVisible(false);
        new content_campus().setVisible(true);
    }//GEN-LAST:event_ST_CampusMouseClicked

    private void ST_OrmawaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ST_OrmawaMouseClicked
        this.setVisible(false);
        new content_ormawa().setVisible(true);
    }//GEN-LAST:event_ST_OrmawaMouseClicked

    private void ST_EventMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ST_EventMouseClicked
        this.setVisible(false);
        new content_event().setVisible(true);
    }//GEN-LAST:event_ST_EventMouseClicked

    private void ST_TechnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ST_TechnoMouseClicked
        this.setVisible(false);
        new content_techno().setVisible(true);
    }//GEN-LAST:event_ST_TechnoMouseClicked

    private void ST_JournalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ST_JournalMouseClicked
        this.setVisible(false);
        new content_journal().setVisible(true);
    }//GEN-LAST:event_ST_JournalMouseClicked

    private void ST_JobMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ST_JobMouseClicked
        this.setVisible(false);
        new content_job().setVisible(true);
    }//GEN-LAST:event_ST_JobMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home_user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ST_Campus;
    private javax.swing.JButton ST_Event;
    private javax.swing.JButton ST_Job;
    private javax.swing.JButton ST_Journal;
    private javax.swing.JButton ST_Ormawa;
    private javax.swing.JButton ST_Techno;
    private javax.swing.JLabel StudentCampus;
    private javax.swing.JLabel StudentEvent;
    private javax.swing.JLabel StudentJob;
    private javax.swing.JLabel StudentJournal;
    private javax.swing.JLabel StudentOrmawa;
    private javax.swing.JLabel StudentTechno;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
